### ISSUE TITLE
Pull Requests are not created in private repositories.

### ISSUE THREAD

**Issue by slime-hatena** [slime-hatena/pull-request-based-release-template#2]
Currently, the draft feature is not supported in private repositories.
It is possible to check and change the draft options, but I don't know where it can get it from...

Or, it is easiest to just leave the bug until it is supported.

https://github.com/slime-hatena/pull-request-based-release-template/blob/404e8fca85139adeec8d4e9ee846103fd023e42a/.github/workflows/repository_initialize.yml#L41-L51

```yaml
      - name: 'Check visibility status'
        run: |
          do something...
          echo "::set-output name=visibility::<true/false>"
...
      - name: 'Create Pull Request'
        uses: repo-sync/pull-request@v2
        with:
          pr_draft: ${{ steps.check.outputs.visibility }}
```
